export const WORD_BANK: { word: string; hint: string }[] = [
  { word: "AARTI", hint: "A Hindu ritual of worship, a part of puja." },
  { word: "ACCHA", hint: "Hindi word for 'good' or 'okay'." },
  { word: "AJWAN", hint: "Carom seeds, a common spice in Indian cooking." },
  { word: "ANAND", hint: "A state of happiness, bliss, or joy." },
  { word: "ARYAN", hint: "Term referring to an ancient noble people or lineage." },
  { word: "ATTAR", hint: "A natural perfume oil, derived from botanical sources." },
  { word: "BADAM", hint: "The Hindi word for almond." },
  { word: "BAGGY", hint: "Loose-fitting trousers, sometimes part of a Salwar Kameez." },
  { word: "BAKRI", hint: "Hindi word for goat, also associated with a major festival." },
  { word: "BAOLI", hint: "An ancient stepwell, often of architectural significance." },
  { word: "BARFI", hint: "A milk-based sweet, often cut into diamond or square shapes." },
  { word: "BASIN", hint: "A large bowl for washing; a river ____ provides water." },
  { word: "BASSI", hint: "A term for something that is stale or not fresh." },
  { word: "BEGUM", hint: "A respectful title for a married Muslim woman of high rank." },
  { word: "BHANG", hint: "An edible preparation of cannabis, associated with Holi." },
  { word: "BHIMA", hint: "One of the five Pandava brothers in the Mahabharata." },
  { word: "BHOOT", hint: "The Hindi word for ghost or spirit." },
  { word: "BIHAR", hint: "A state in Eastern India." },
  { word: "BIJLI", hint: "The Hindi word for electricity or lightning." },
  { word: "BISWA", hint: "A traditional unit of land measurement." },
  { word: "CHAKR", hint: "A spinning discus-like weapon, famously wielded by Vishnu." },
  { word: "CHANA", hint: "Chickpeas, a staple in many Indian dishes." },
  { word: "CHULA", hint: "A traditional cooking stove, often made of mud or clay." },
  { word: "CHUTI", hint: "Hindi word for holiday or leave from work." },
  { word: "CURRY", hint: "A dish with a sauce seasoned with spices." },
  { word: "DAHEJ", hint: "The practice of giving a dowry." },
  { word: "DALIT", hint: "A member of the lowest caste in the traditional Hindu system." },
  { word: "DAMRU", hint: "A small two-headed drum associated with Lord Shiva." },
  { word: "DARZI", hint: "A tailor or seamstress." },
  { word: "DELHI", hint: "The capital city of India." },
  { word: "DEVER", hint: "Hindi term for a husband's younger brother." },
  { word: "DHABA", hint: "A roadside eatery, especially on highways." },
  { word: "DHOTI", hint: "A traditional men's garment wrapped around the waist." },
  { word: "DIWAN", hint: "A royal court or a high-ranking government minister." },
  { word: "DOHRA", hint: "A couplet or a specific form of Hindi poetry." },
  { word: "DULHA", hint: "The Hindi word for a groom." },
  { word: "DURGA", hint: "A major Hindu goddess, a form of the divine mother." },
  { word: "GANGA", hint: "The most sacred river in Hinduism." },
  { word: "GARAM", hint: "Hindi word for 'hot', often in '____ Masala'." },
  { word: "GEELA", hint: "The Hindi word for 'wet' or 'moist'." },
  { word: "GULAB", hint: "The Hindi word for rose, as in ____ Jamun." },
  { word: "GUPTA", hint: "A powerful ancient Indian dynasty." },
  { word: "HALDI", hint: "Turmeric, a bright yellow spice." },
  { word: "HALWA", hint: "A dense, sweet confection, often made from flour or semolina." },
  { word: "HARAM", hint: "Something forbidden or proscribed by Islamic law." },
  { word: "HENNA", hint: "A paste used for temporary body art, especially for weddings." },
  { word: "INDUS", hint: "A major river that flows through South Asia." },
  { word: "JALSA", hint: "A celebration, gathering, or festive event." },
  { word: "JEEPS", hint: "A rugged vehicle, often used in rural or hilly areas." },
  { word: "JHOLI", hint: "A small cloth bag or satchel, often carried by sadhus." },
  { word: "KADAI", hint: "A type of thick, circular, and deep cooking pot." },
  { word: "KADAM", hint: "A step or a footstep." },
  { word: "KARMA", hint: "The sum of a person's actions and their consequences." },
  { word: "KEBAB", hint: "Grilled skewers of meat or vegetables." },
  { word: "KHADI", hint: "Hand-spun and hand-woven cloth, promoted by Gandhi." },
  { word: "KHEER", hint: "A sweet rice pudding, a popular dessert." },
  { word: "KHELA", hint: "The Hindi word for a game or sport." },
  { word: "KHOYA", hint: "Dried evaporated milk solids, used in sweets." },
  { word: "LADDU", hint: "A sphere-shaped sweet made from flour and sugar." },
  { word: "LASSI", hint: "A popular yogurt-based drink, sweet or salty." },
  { word: "LOBAN", hint: "A type of frankincense resin used as incense." },
  { word: "LOTUS", hint: "The national flower of India, a symbol of purity." },
  { word: "MAHAL", hint: "The Hindi word for palace." },
  { word: "MAIDA", hint: "Refined wheat flour used for making naan and bhature." },
  { word: "MALAI", hint: "Cream, often used in rich curries and desserts." },
  { word: "MANGO", hint: "The 'king of fruits', and India's national fruit." },
  { word: "MASKA", hint: "Hindi word for butter, often with 'bun'." },
  { word: "MATAR", hint: "Green peas, a common vegetable in curries." },
  { word: "MATHA", hint: "A monastery or religious institution." },
  { word: "MAUSA", hint: "Maternal uncle, mother's sister's husband." },
  { word: "MIRCH", hint: "The Hindi word for chili pepper." },
  { word: "MITHA", hint: "The Hindi word for 'sweet'." },
  { word: "MURTI", hint: "An idol or statue of a deity." },
  { word: "NAWAB", hint: "A title for a sovereign ruler, often of a princely state." },
  { word: "PAGAL", hint: "A colloquial term for 'crazy' or 'mad'." },
  { word: "PAGDI", hint: "A traditional turban or headwear." },
  { word: "PAISE", hint: "Plural of paisa, a monetary unit." },
  { word: "PAKKA", hint: "Colloquial term for 'solid', 'genuine', or 'permanent'." },
  { word: "PAANI", hint: "The Hindi word for water." },
  { word: "PATNA", hint: "The capital city of the state of Bihar." },
  { word: "PEPAL", hint: "A sacred fig tree in India." },
  { word: "RAITA", hint: "A cooling side dish made with yogurt and vegetables." },
  { word: "RAKHI", hint: "A sacred thread tied by a sister on her brother's wrist." },
  { word: "ROGAN", hint: "A type of rich, aromatic curry, as in '____ Josh'." },
  { word: "RUPEE", hint: "The official currency of India." },
  { word: "SABJI", hint: "A cooked vegetable dish." },
  { word: "SALON", hint: "A shop for hairdressing or beauty treatments." },
  { word: "SAPNA", hint: "The Hindi word for a dream." },
  { word: "SAREE", hint: "A traditional garment worn by women." },
  { word: "SARSO", hint: "The Hindi word for mustard, as in '____ da Saag'." },
  { word: "SEVAK", hint: "A servant, volunteer, or devotee." },
  { word: "SITAR", hint: "A long-necked string instrument." },
  { word: "SONAR", hint: "A goldsmith or jeweler." },
  { word: "SURAT", hint: "A large city in Gujarat, famous for diamonds and textiles." },
  { word: "SUTRA", hint: "An aphorism or a collection of them in ancient texts." },
  { word: "SWAMI", hint: "A Hindu religious teacher or ascetic." },
  { word: "TABLA", hint: "A pair of small hand drums." },
  { word: "TANDO", hint: "A clay oven used for baking and cooking, short for Tandoor." },
  { word: "THALI", hint: "A platter serving a variety of dishes." },
  { word: "TIKKA", hint: "Small pieces of marinated food, grilled." },
  { word: "TULSI", hint: "Holy basil, a sacred plant in Hinduism." },
  { word: "ZARDA", hint: "A sweet, fragrant rice dish, often colored yellow or orange." }
];
